giochi = [

"  1 | The Oregon Trail                                    | Strategy                | MECC                                                       | HP 2100                                           ",
"  2 | Pong                                                | Sports                  | Atari, Inc.                                                | Arcade                                            ",
"  3 | Combat                                              | Top-down shooter        | Atari, Inc.                                                | Atari 2600                                        ",
"  4 | Zork                                                | Adventure               | Infocom                                                    | PDP-10                                            ",
"  5 | Space Invaders                                      | Shoot 'em up            | Taito                                                      | Arcade                                            ",
"  6 | Asteroids                                           | Shoot 'em up            | Atari, Inc.                                                | Arcade                                            ",
"  7 | Adventure                                           | Action-adventure        | Atari, Inc.                                                | Atari 2600                                        ",
"  8 | Battlezone                                          | Vehicle simulation      | Atari, Inc.                                                | Arcade                                            ",
"  9 | Missile Command                                     | Shoot 'em up            | Atari, Inc.                                                | Arcade                                            ",
" 10 | Pac-Man                                             | Maze                    | Namco                                                      | Arcade                                            ",
" 11 | Centipede                                           | Shoot 'em up            | Atari, Inc.                                                | Arcade                                            ",
" 12 | Defender                                            | Shoot 'em up            | Williams Entertainment                                     | Arcade                                            ",
" 13 | Donkey Kong                                         | Platform                | Nintendo                                                   | Arcade                                            ",
" 14 | Frogger                                             | Action                  | Konami/Sega                                                | Arcade                                            ",
" 15 | Galaga                                              | Shoot 'em up            | Namco                                                      | Arcade                                            ",
" 16 | Tempest                                             | Shoot 'em up            | Atari, Inc.                                                | Arcade                                            ",
" 17 | Wizardry: Proving Grounds of the Mad Overlord       | Role-playing            | Sir-Tech                                                   | Apple II                                          ",
" 18 | Joust                                               | Action                  | Williams                                                   | Arcade                                            ",
" 19 | Ms. Pac-Man                                         | Maze                    | Midway                                                     | Arcade                                            ",
" 20 | Pitfall!                                            | Platform                | Activision                                                 | Atari 2600                                        ",
" 21 | Robotron: 2084                                      | Top-down shooter        | Williams                                                   | Arcade                                            ",
" 22 | Archon: The Light and the Dark                      | Strategy                | Electronic Arts                                            | Atari 8-bit family                                ",
" 23 | Lode Runner                                         | Platform                | Broderbund                                                 | Apple II                                          ",
" 24 | M.U.L.E.                                            | Business simulation     | Electronic Arts                                            | Atari 8-bit family                                ",
" 25 | Star Wars                                           | Shoot 'em up            | Atari, Inc.                                                | Arcade                                            ",
" 26 | Elite                                               | Space flight simulator  | Acornsoft                                                  | BBC Micro                                         ",
" 27 | Marble Madness                                      | Action                  | Atari Games                                                | Arcade                                            ",
" 28 | Tetris                                              | Puzzle                  | Elorg                                                      | Electronika 60                                    ",
" 29 | Gauntlet                                            | Action role-playing     | Atari Games                                                | Arcade                                            ",
" 30 | Ghosts 'n Goblins                                   | Platform                | Capcom                                                     | Arcade                                            ",
" 31 | Super Mario Bros.                                   | Platform                | Nintendo                                                   | NES                                               ",
" 32 | Ultima IV: Quest of the Avatar                      | Role-playing            | Origin Systems                                             | Apple II                                          ",
" 33 | Arkanoid                                            | Block breaker           | Taito                                                      | Arcade                                            ",
" 34 | Bubble Bobble                                       | Platform                | Taito                                                      | Arcade                                            ",
" 35 | The Legend of Zelda                                 | Action-adventure        | Nintendo                                                   | NES                                               ",
" 36 | Out Run                                             | Racing                  | Sega                                                       | Arcade                                            ",
" 37 | Contra                                              | Run and gun             | Konami                                                     | Arcade                                            ",
" 38 | Double Dragon                                       | Beat 'em up             | Technos Japan                                              | Arcade                                            ",
" 39 | Dungeon Master                                      | Role-playing            | FTL Games                                                  | Atari ST                                          ",
" 40 | Mike Tyson's Punch-Out!!                            | Sports                  | Nintendo                                                   | NES                                               ",
" 41 | R-Type                                              | Shoot 'em up            | Irem                                                       | Arcade                                            ",
" 42 | Sid Meier's Pirates!                                | Action-adventure        | MicroProse                                                 | Commodore 64                                      ",
" 43 | Mega Man 2                                          | Platform                | Capcom                                                     | NES                                               ",
" 44 | Ninja Gaiden                                        | Platform                | Tecmo                                                      | NES                                               ",
" 45 | Super Mario Bros. 3                                 | Platform                | Nintendo                                                   | NES                                               ",
" 46 | Final Fight                                         | Beat 'em up             | Capcom                                                     | Arcade                                            ",
" 47 | Populous                                            | God game                | Electronic Arts                                            | Amiga                                             ",
" 48 | Prince of Persia                                    | Platform                | Broderbund                                                 | Apple II                                          ",
" 49 | SimCity                                             | City-building           | Maxis                                                      | Amiga, Macintosh                                  ",
" 50 | The Secret of Monkey Island                         | Adventure               | LucasArts                                                  | PC                                                ",
" 51 | Speedball 2: Brutal Deluxe                          | Sports                  | Image Works                                                | Atari ST                                          ",
" 52 | Super Mario World                                   | Platform                | Nintendo                                                   | Super NES                                         ",
" 53 | Wing Commander                                      | Space flight simulator  | Origin Systems                                             | PC                                                ",
" 54 | Another World                                       | Platform                | Delphine Software                                          | Amiga, Atari ST                                   ",
" 55 | Civilization                                        | Turn-based strategy     | MicroProse                                                 | PC                                                ",
" 56 | Final Fantasy IV                                    | Role-playing            | Square                                                     | Super NES                                         ",
" 57 | The Legend of Zelda: A Link to the Past             | Action-adventure        | Nintendo                                                   | Super NES                                         ",
" 58 | Lemmings                                            | Puzzle                  | Psygnosis                                                  | Amiga                                             ",
" 59 | Micro Machines                                      | Racing                  | Camerica                                                   | NES                                               ",
" 60 | Monkey Island 2: LeChuck's Revenge                  | Adventure               | LucasArts                                                  | PC                                                ",
" 61 | Sonic the Hedgehog                                  | Platform                | Sega                                                       | Sega Genesis                                      ",
" 62 | Street Fighter II                                   | Fighting                | Capcom                                                     | Arcade                                            ",
" 63 | Super Castlevania IV                                | Platform                | Konami                                                     | Super NES                                         ",
" 64 | Alone in the Dark                                   | Survival horror         | Infogrames                                                 | PC                                                ",
" 65 | Contra III: The Alien Wars                          | Run and gun             | Konami                                                     | Super NES                                         ",
" 66 | Dune II                                             | Real-time strategy      | Virgin Games                                               | PC                                                ",
" 67 | Flashback                                           | Platform                | U.S. Gold                                                  | Amiga                                             ",
" 68 | Indiana Jones and the Fate of Atlantis              | Adventure               | LucasArts                                                  | PC                                                ",
" 69 | Mortal Kombat                                       | Fighting                | Midway                                                     | Arcade                                            ",
" 70 | Sensible Soccer                                     | Sports                  | Renegade Software                                          | Amiga, Atari ST                                   ",
" 71 | Sonic the Hedgehog 2                                | Platform                | Sega                                                       | Sega Genesis                                      ",
" 72 | Star Control II                                     | Action-adventure        | Accolade                                                   | PC                                                ",
" 73 | Streets of Rage 2                                   | Beat 'em up             | Sega                                                       | Sega Genesis                                      ",
" 74 | Super Mario Kart                                    | Kart racing             | Nintendo                                                   | Super NES                                         ",
" 75 | Ultima VII: The Black Gate                          | Role-playing            | Origin Systems                                             | PC                                                ",
" 76 | Virtua Racing                                       | Racing                  | Sega                                                       | Arcade                                            ",
" 77 | Wolfenstein 3D                                      | First-person shooter    | Apogee Software                                            | PC                                                ",
" 78 | Day of the Tentacle                                 | Adventure               | LucasArts                                                  | PC                                                ",
" 79 | Daytona USA                                         | Racing                  | Sega                                                       | Arcade                                            ",
" 80 | Doom                                                | First-person shooter    | id Software                                                | PC                                                ",
" 81 | Gunstar Heroes                                      | Run and gun             | Sega                                                       | Sega Genesis                                      ",
" 82 | The Legend of Zelda: Link's Awakening               | Action-adventure        | Nintendo                                                   | Game Boy                                          ",
" 83 | Mega Man X                                          | Platform                | Capcom                                                     | Super NES                                         ",
" 84 | Mortal Kombat II                                    | Fighting                | Midway                                                     | Arcade                                            ",
" 85 | Myst                                                | Adventure               | Broderbund                                                 | Macintosh                                         ",
" 86 | NBA Jam                                             | Sports                  | Midway                                                     | Arcade                                            ",
" 87 | Phantasy Star IV                                    | Role-playing            | Sega                                                       | Sega Genesis                                      ",
" 88 | Ridge Racer                                         | Racing                  | Namco                                                      | Arcade                                            ",
" 89 | Sam & Max Hit the Road                              | Adventure               | LucasArts                                                  | PC                                                ",
" 90 | Secret of Mana                                      | Action role-playing     | Square                                                     | Super NES                                         ",
" 91 | Samurai Shodown                                     | Fighting                | SNK                                                        | Arcade                                            ",
" 92 | SimCity 2000                                        | City-building           | Maxis                                                      | Macintosh                                         ",
" 93 | Star Fox                                            | Shoot 'em up            | Nintendo                                                   | Super NES                                         ",
" 94 | Syndicate                                           | Real-time tactics       | Electronic Arts                                            | Amiga, PC                                         ",
" 95 | Donkey Kong Country                                 | Platform                | Nintendo                                                   | Super NES                                         ",
" 96 | Doom II                                             | First-person shooter    | GT Interactive                                             | PC                                                ",
" 97 | EarthBound                                          | Role-playing            | Nintendo                                                   | Super NES                                         ",
" 98 | Final Fantasy VI                                    | Role-playing            | Square                                                     | Super NES                                         ",
" 99 | Sega Rally Championship                             | Racing                  | Sega                                                       | Arcade                                            ",
"100 | Sensible World of Soccer                            | Sports                  | Renegade Software                                          | Amiga                                             ",
"101 | Star Wars: TIE Fighter                              | Space flight simulator  | LucasArts                                                  | PC                                                ",
"102 | Super Metroid                                       | Action-adventure        | Nintendo                                                   | Super NES                                         ",
"103 | Tempest 2000                                        | Shoot 'em up            | Atari Corporation                                          | Atari Jaguar                                      ",
"104 | Theme Park                                          | Business simulation     | Electronic Arts                                            | Amiga, PC                                         ",
"105 | Virtua Fighter 2                                    | Fighting                | Sega                                                       | Arcade                                            ",
"106 | X-COM: UFO Defense                                  | Turn-based strategy     | MicroProse                                                 | PC                                                ",
"107 | Chrono Trigger                                      | Role-playing            | Square                                                     | Super NES                                         ",
"108 | Command & Conquer                                   | Real-time strategy      | Virgin Interactive                                         | PC                                                ",
"109 | MechWarrior 2: 31st Century Combat                  | Vehicle simulation      | Activision                                                 | PC                                                ",
"110 | Warcraft II: Tides of Darkness                      | Real-time strategy      | Blizzard Entertainment                                     | PC                                                ",
"111 | Wipeout                                             | Racing                  | Psygnosis                                                  | PC, PlayStation                                   ",
"112 | Worms                                               | Artillery               | Ocean Software                                             | Amiga                                             ",
"113 | Yoshi's Island                                      | Platform                | Nintendo                                                   | Super NES                                         ",
"114 | Civilization II                                     | Turn-based strategy     | MicroProse                                                 | PC                                                ",
"115 | Command & Conquer: Red Alert                        | Real-time strategy      | Virgin Interactive                                         | PC                                                ",
"116 | Duke Nukem 3D                                       | First-person shooter    | GT Interactive                                             | PC                                                ",
"117 | Mario Kart 64                                       | Kart racing             | Nintendo                                                   | Nintendo 64                                       ",
"118 | Nights into Dreams...                               | Action                  | Sega                                                       | Saturn                                            ",
"119 | PaRappa the Rapper                                  | Rhythm                  | Sony Computer Entertainment                                | PlayStation                                       ",
"120 | Pokémon Redand Blue                                 | Role-playing            | Nintendo                                                   | Game Boy                                          ",
"121 | Quake                                               | First-person shooter    | GT Interactive                                             | PC                                                ",
"122 | Resident Evil                                       | Survival horror         | Capcom                                                     | PlayStation                                       ",
"123 | Super Mario 64                                      | Platform                | Nintendo                                                   | Nintendo 64                                       ",
"124 | Tekken 3                                            | Fighting                | Namco                                                      | Arcade                                            ",
"125 | Tomb Raider                                         | Action-adventure        | Eidos Interactive                                          | Saturn, PC, PlayStation                           ",
"126 | Wave Race 64                                        | Racing                  | Nintendo                                                   | Nintendo 64                                       ",
"127 | Wipeout 2097                                        | Racing                  | Psygnosis                                                  | PlayStation                                       ",
"128 | Age of Empires                                      | Real-time strategy      | Microsoft                                                  | PC                                                ",
"129 | Castlevania: Symphony of the Night                  | Action-adventure        | Konami                                                     | PlayStation                                       ",
"130 | Diablo                                              | Action role-playing     | Blizzard Entertainment                                     | PC                                                ",
"131 | Fallout                                             | Role-playing            | Interplay Entertainment                                    | PC                                                ",
"132 | Final Fantasy Tactics                               | Tactical role-playing   | Square                                                     | PlayStation                                       ",
"133 | Final Fantasy VII                                   | Role-playing            | Square                                                     | PlayStation                                       ",
"134 | GoldenEye 007                                       | First-person shooter    | Nintendo                                                   | Nintendo 64                                       ",
"135 | Gran Turismo                                        | Racing                  | Sony Computer Entertainment                                | PlayStation                                       ",
"136 | Grand Theft Auto                                    | Action-adventure        | BMG Interactive                                            | PC                                                ",
"137 | Quake II                                            | First-person shooter    | Activision                                                 | PC                                                ",
"138 | Star Fox 64                                         | Shoot 'em up            | Nintendo                                                   | Nintendo 64                                       ",
"139 | Star Wars Jedi Knight: Dark Forces II               | First-person shooter    | LucasArts                                                  | PC                                                ",
"140 | Total Annihilation                                  | Real-time strategy      | Cavedog Entertainment                                      | PC                                                ",
"141 | Ultima Online                                       | MMORPG                  | Electronic Arts                                            | PC                                                ",
"142 | Baldur's Gate                                       | Role-playing            | Black Isle Studios                                         | PC                                                ",
"143 | Crash Bandicoot: Warped                             | Platform                | Sony Computer Entertainment                                | PlayStation                                       ",
"144 | Dance Dance Revolution                              | Rhythm                  | Konami                                                     | Arcade                                            ",
"145 | Fallout 2                                           | Role-playing            | Interplay Entertainment                                    | PC                                                ",
"146 | Grim Fandango                                       | Adventure               | LucasArts                                                  | PC                                                ",
"147 | Half-Life                                           | First-person shooter    | Sierra Studios                                             | PC                                                ",
"148 | The Legend of Zelda: Ocarina of Time                | Action-adventure        | Nintendo                                                   | Nintendo 64                                       ",
"149 | Metal Gear Solid                                    | Stealth                 | Konami                                                     | PlayStation                                       ",
"150 | Panzer Dragoon Saga                                 | Role-playing            | Sega                                                       | Saturn                                            ",
"151 | Resident Evil 2                                     | Survival horror         | Capcom                                                     | PlayStation                                       ",
"152 | Soulcalibur                                         | Fighting                | Namco                                                      | Arcade                                            ",
"153 | StarCraft                                           | Real-time strategy      | Blizzard Entertainment                                     | PC                                                ",
"154 | Suikoden II                                         | Role-playing            | Konami                                                     | PlayStation                                       ",
"155 | Thief: The Dark Project                             | Stealth                 | Eidos Interactive                                          | PC                                                ",
"156 | Age of Empires II                                   | Real-time strategy      | Microsoft                                                  | PC                                                ",
"157 | EverQuest                                           | MMORPG                  | Sony Online Entertainment                                  | PC                                                ",
"158 | Homeworld                                           | Real-time strategy      | Sierra Studios                                             | PC                                                ",
"159 | Planescape: Torment                                 | Role-playing            | Interplay Entertainment                                    | PC                                                ",
"160 | Pokémon Goldand Silver                              | Role-playing            | Nintendo                                                   | Game Boy Color                                    ",
"161 | Quake III: Arena                                    | First-person shooter    | Activision                                                 | PC                                                ",
"162 | Shenmue                                             | Adventure               | Sega                                                       | Dreamcast                                         ",
"163 | Silent Hill                                         | Survival horror         | Konami                                                     | PlayStation                                       ",
"164 | System Shock 2                                      | First-person shooter    | Electronic Arts                                            | PC                                                ",
"165 | Unreal Tournament                                   | First-person shooter    | GT Interactive                                             | PC                                                ",
"166 | Baldur's Gate II: Shadows of Amn                    | Role-playing            | Black Isle Studios                                         | PC                                                ",
"167 | Counter-Strike                                      | First-person shooter    | Valve                                                      | PC                                                ",
"168 | Deus Ex                                             | Action role-playing     | Eidos Interactive                                          | PC                                                ",
"169 | Diablo II                                           | Action role-playing     | Blizzard Entertainment                                     | PC                                                ",
"170 | Jet Set Radio                                       | Platform                | Sega                                                       | Dreamcast                                         ",
"171 | The Legend of Zelda: Majora's Mask                  | Action-adventure        | Nintendo                                                   | Nintendo 64                                       ",
"172 | Marvel vs. Capcom 2: New Age of Heroes              | Fighting                | Capcom                                                     | Arcade                                            ",
"173 | The Sims                                            | Life simulation         | Electronic Arts                                            | PC                                                ",
"174 | Thief II: The Metal Age                             | Stealth                 | Eidos Interactive                                          | PC                                                ",
"175 | Tony Hawk's Pro Skater 2                            | Sports                  | Activision                                                 | PlayStation                                       ",
"176 | Advance Wars                                        | Turn-based tactics      | Nintendo                                                   | Game Boy Advance                                  ",
"177 | Animal Crossing                                     | Life simulation         | Nintendo                                                   | GameCube                                          ",
"178 | Devil May Cry                                       | Action-adventure        | Capcom                                                     | PlayStation 2                                     ",
"179 | Final Fantasy X                                     | Role-playing            | Square                                                     | PlayStation 2                                     ",
"180 | Gran Turismo 3: A-Spec                              | Racing                  | Sony Computer Entertainment                                | PlayStation 2                                     ",
"181 | Grand Theft Auto III                                | Action-adventure        | Rockstar Games                                             | PlayStation 2                                     ",
"182 | Halo: Combat Evolved                                | First-person shooter    | Microsoft Game Studios                                     | Xbox                                              ",
"183 | Ico                                                 | Action-adventure        | Sony Computer Entertainment                                | PlayStation 2                                     ",
"184 | Ikaruga                                             | Shoot 'em up            | Treasure                                                   | Arcade                                            ",
"185 | Max Payne                                           | Third-person shooter    | Gathering of Developers                                    | PC                                                ",
"186 | Metal Gear Solid 2: Sons of Liberty                 | Stealth                 | Konami                                                     | PlayStation 2                                     ",
"187 | Phoenix Wright: Ace Attorney                        | Adventure               | Capcom                                                     | Game Boy Advance                                  ",
"188 | Rez                                                 | Shoot 'em up            | Sega                                                       | Dreamcast, PlayStation 2                          ",
"189 | Silent Hill 2                                       | Survival horror         | Konami                                                     | PlayStation 2                                     ",
"190 | Super Smash Bros. Melee                             | Fighting                | Nintendo                                                   | GameCube                                          ",
"191 | Tony Hawk's Pro Skater 3                            | Sports                  | Activision                                                 | PlayStation, PlayStation 2                        ",
"192 | Battlefield 1942                                    | First-person shooter    | Electronic Arts                                            | PC                                                ",
"193 | The Elder Scrolls III: Morrowind                    | Action role-playing     | Bethesda Softworks                                         | PC                                                ",
"194 | Eternal Darkness: Sanity's Requiem                  | Survival horror         | Nintendo                                                   | GameCube                                          ",
"195 | Grand Theft Auto: Vice City                         | Action-adventure        | Rockstar Games                                             | PlayStation 2                                     ",
"196 | Kingdom Hearts                                      | Action role-playing     | Square                                                     | PlayStation 2                                     ",
"197 | The Legend of Zelda: The Wind Waker                 | Action-adventure        | Nintendo                                                   | GameCube                                          ",
"198 | Metroid Prime                                       | Action-adventure        | Nintendo                                                   | GameCube                                          ",
"199 | Soulcalibur II                                      | Fighting                | Namco                                                      | Arcade                                            ",
"200 | Tom Clancy's Splinter Cell                          | Stealth                 | Ubisoft                                                    | Xbox                                              ",
"201 | Warcraft III: Reign of Chaos                        | Real-time strategy      | Blizzard Entertainment                                     | PC, Macintosh                                     ",
"202 | Beyond Good & Evil                                  | Action-adventure        | Ubisoft                                                    | PlayStation 2                                     ",
"203 | F-Zero GX                                           | Racing                  | Nintendo                                                   | GameCube                                          ",
"204 | Max Payne 2: The Fall of Max Payne                  | Third-person shooter    | Rockstar Games                                             | PC                                                ",
"205 | Prince of Persia: The Sands of Time                 | Action-adventure        | Ubisoft                                                    | PlayStation 2                                     ",
"206 | Star Wars: Knights of the Old Republic              | Role-playing            | LucasArts                                                  | Xbox                                              ",
"207 | WarioWare, Inc.: Mega Microgames!                   | Action                  | Nintendo                                                   | Game Boy Advance                                  ",
"208 | Burnout 3: Takedown                                 | Racing                  | Electronic Arts                                            | PlayStation 2, Xbox                               ",
"209 | The Chronicles of Riddick: Escape from Butcher Bay  | Stealth                 | Vivendi Universal Games                                    | Xbox                                              ",
"210 | Dragon Quest VIII                                   | Role-playing            | Square Enix                                                | PlayStation 2                                     ",
"211 | Gran Turismo 4                                      | Racing                  | Sony Computer Entertainment                                | PlayStation 2                                     ",
"212 | Grand Theft Auto: San Andreas                       | Action-adventure        | Rockstar Games                                             | PlayStation 2                                     ",
"213 | Half-Life 2                                         | First-person shooter    | Valve                                                      | PC                                                ",
"214 | Halo 2                                              | First-person shooter    | Microsoft Game Studios                                     | Xbox                                              ",
"215 | Katamari Damacy                                     | Action                  | Namco                                                      | PlayStation 2                                     ",
"216 | Metal Gear Solid 3: Snake Eater                     | Stealth                 | Konami                                                     | PlayStation 2                                     ",
"217 | Rome: Total War                                     | Strategy                | Activision                                                 | PC                                                ",
"218 | The Sims 2                                          | Life simulation         | Electronic Arts                                            | PC                                                ",
"219 | World of Warcraft                                   | MMORPG                  | Blizzard Entertainment                                     | PC, Macintosh                                     ",
"220 | Call of Duty 2                                      | First-person shooter    | Activision                                                 | PC                                                ",
"221 | Civilization IV                                     | Turn-based strategy     | 2K Games                                                   | PC                                                ",
"222 | Devil May Cry 3: Dante's Awakening                  | Action-adventure        | Capcom                                                     | PlayStation 2                                     ",
"223 | God of War                                          | Action-adventure        | Sony Computer Entertainment                                | PlayStation 2                                     ",
"224 | Guitar Hero                                         | Rhythm                  | RedOctane                                                  | PlayStation 2                                     ",
"225 | Psychonauts                                         | Platform                | Majesco                                                    | PC, Xbox                                          ",
"226 | Resident Evil 4                                     | Survival horror         | Capcom                                                     | GameCube                                          ",
"227 | Shadow of the Colossus                              | Action-adventure        | Sony Computer Entertainment                                | PlayStation 2                                     ",
"228 | Tom Clancy's Splinter Cell: Chaos Theory            | Stealth                 | Ubisoft                                                    | GameCube, PC, PlayStation 2, Xbox                 ",
"229 | Company of Heroes                                   | Real-time strategy      | THQ                                                        | PC                                                ",
"230 | The Elder Scrolls IV: Oblivion                      | Action role-playing     | 2K Games, Bethesda Softworks                               | PC, Xbox 360                                      ",
"231 | Gears of War                                        | Third-person shooter    | Microsoft Game Studios                                     | Xbox 360                                          ",
"232 | Hitman: Blood Money                                 | Stealth                 | Eidos Interactive                                          | PC, PlayStation 2, Xbox, Xbox 360                 ",
"233 | The Legend of Zelda: Twilight Princess              | Action-adventure        | Nintendo                                                   | GameCube, Wii                                     ",
"234 | Wii Sports                                          | Sports                  | Nintendo                                                   | Wii                                               ",
"235 | BioShock                                            | First-person shooter    | 2K Games                                                   | PC, Xbox 360                                      ",
"236 | Call of Duty 4: Modern Warfare                      | First-person shooter    | Activision                                                 | PC, PlayStation 3, Xbox 360                       ",
"237 | God of War II                                       | Action-adventure        | Sony Computer Entertainment                                | PlayStation 2                                     ",
"238 | Halo 3                                              | First-person shooter    | Microsoft Game Studios                                     | Xbox 360                                          ",
"239 | Mass Effect                                         | Action role-playing     | Microsoft Game Studios                                     | Xbox 360                                          ",
"240 | Portal                                              | Puzzle-platformer       | Valve                                                      | PC, Xbox 360                                      ",
"241 | Rock Band                                           | Rhythm                  | MTV Games                                                  | PlayStation 3, Xbox 360                           ",
"242 | Super Mario Galaxy                                  | Platform                | Nintendo                                                   | Wii                                               ",
"243 | Team Fortress 2                                     | First-person shooter    | Valve                                                      | PC, Xbox 360                                      ",
"244 | The World Ends with You                             | Role-playing            | Square Enix                                                | Nintendo DS                                       ",
"245 | Braid                                               | Puzzle-platformer       | Microsoft Game Studios                                     | Xbox 360                                          ",
"246 | Burnout Paradise                                    | Racing                  | Electronic Arts                                            | PC, PlayStation 3, Xbox 360                       ",
"247 | Dead Space                                          | Survival horror         | Electronic Arts                                            | PlayStation 3, Xbox 360                           ",
"248 | Fable II                                            | Action role-playing     | Microsoft Game Studios                                     | Xbox 360                                          ",
"249 | Fallout 3                                           | Action role-playing     | Bethesda Softworks                                         | PC, PlayStation 3, Xbox 360                       ",
"250 | Gears of War 2                                      | Third-person shooter    | Microsoft Game Studios                                     | Xbox 360                                          ",
"251 | Grand Theft Auto IV                                 | Action-adventure        | Rockstar Games                                             | PlayStation 3, Xbox 360                           ",
"252 | Left 4 Dead                                         | First-person shooter    | Valve                                                      | PC, Xbox 360                                      ",
"253 | LittleBigPlanet                                     | Platform                | Sony Computer Entertainment                                | PlayStation 3                                     ",
"254 | Persona 4                                           | Role-playing            | Atlus                                                      | PlayStation 2                                     ",
"255 | Rock Band 2                                         | Rhythm                  | MTV Games                                                  | Xbox 360                                          ",
"256 | Spelunky                                            | Platform                | Derek Yu                                                   | PC                                                ",
"257 | Street Fighter IV                                   | Fighting                | Capcom                                                     | Arcade                                            ",
"258 | Valkyria Chronicles                                 | Tactical role-playing   | Sega                                                       | PlayStation 3                                     ",
"259 | Angry Birds                                         | Puzzle                  | Rovio Entertainment                                        | Maemo, iOS                                        ",
"260 | Assassin's Creed II                                 | Action-adventure        | Ubisoft                                                    | PlayStation 3, Xbox 360                           ",
"261 | Batman: Arkham Asylum                               | Action-adventure        | Eidos Interactive, Warner Bros. Interactive Entertainment  | PlayStation 3, Xbox 360                           ",
"262 | Bayonetta                                           | Action                  | Sega                                                       | PlayStation 3, Xbox 360                           ",
"263 | Borderlands                                         | Action role-playing     | 2K Games                                                   | PC, PlayStation 3, Xbox 360                       ",
"264 | Demon's Souls                                       | Action role-playing     | Sony Computer Entertainment                                | PlayStation 3                                     ",
"265 | Dragon Age: Origins                                 | Role-playing            | Electronic Arts                                            | PC, PlayStation 3, Xbox 360                       ",
"266 | League of Legends                                   | MOBA                    | Riot Games                                                 | PC                                                ",
"267 | Left 4 Dead 2                                       | First-person shooter    | Valve                                                      | PC, Xbox 360                                      ",
"268 | Plants vs. Zombies                                  | Tower defense           | PopCap Games                                               | PC, Macintosh                                     ",
"269 | Uncharted 2: Among Thieves                          | Action-adventure        | Sony Computer Entertainment                                | PlayStation 3                                     ",
"270 | God of War III                                      | Action-adventure        | Sony Computer Entertainment                                | PlayStation 3                                     ",
"271 | Heavy Rain                                          | Adventure               | Sony Computer Entertainment                                | PlayStation 3                                     ",
"272 | Limbo                                               | Platform                | Microsoft Game Studios                                     | Xbox 360                                          ",
"273 | Mass Effect 2                                       | Action role-playing     | Electronic Arts                                            | PC, Xbox 360                                      ",
"274 | Red Dead Redemption                                 | Action-adventure        | Rockstar Games                                             | PlayStation 3, Xbox 360                           ",
"275 | Rock Band 3                                         | Rhythm                  | MTV Games                                                  | Nintendo DS, PlayStation 3, Xbox 360, Wii         ",
"276 | StarCraft II: Wings of Liberty                      | Real-time strategy      | Blizzard Entertainment                                     | PC, Macintosh                                     ",
"277 | Super Mario Galaxy 2                                | Platform                | Nintendo                                                   | Wii                                               ",
"278 | Super Meat Boy                                      | Platform                | Team Meat                                                  | Xbox 360                                          ",
"279 | Xenoblade Chronicles                                | Action role-playing     | Nintendo                                                   | Wii                                               ",
"280 | Batman: Arkham City                                 | Action-adventure        | Warner Bros. Interactive Entertainment                     | PlayStation 3, Xbox 360                           ",
"281 | Dark Souls                                          | Action role-playing     | Namco Bandai Games                                         | PlayStation 3, Xbox 360                           ",
"282 | The Elder Scrolls V: Skyrim                         | Action role-playing     | Bethesda Softworks                                         | PC, PlayStation 3, Xbox 360                       ",
"283 | Minecraft                                           | Sandbox                 | Mojang                                                     | PC                                                ",
"284 | Portal 2                                            | Puzzle-platformer       | Valve                                                      | PC, PlayStation 3, Xbox 360                       ",
"285 | Dishonored                                          | Stealth                 | Bethesda Softworks                                         | PC, PlayStation 3, Xbox 360                       ",
"286 | Far Cry 3                                           | First-person shooter    | Ubisoft                                                    | PC, PlayStation 3, Xbox 360                       ",
"287 | Fire Emblem: Awakening                              | Tactical role-playing   | Nintendo                                                   | Nintendo 3DS                                      ",
"288 | Journey                                             | Adventure               | Sony Computer Entertainment                                | PlayStation 3                                     ",
"289 | Hotline Miami                                       | Action                  | Devolver Digital                                           | PC                                                ",
"290 | The Walking Dead                                    | Adventure               | Telltale Games                                             | PC, PlayStation 3, Xbox 360                       ",
"291 | XCOM: Enemy Unknown                                 | Turn-based strategy     | 2K Games                                                   | PC, PlayStation 3, Xbox 360                       ",
"292 | BioShock Infinite                                   | First-person shooter    | 2K Games                                                   | PC, PlayStation 3, Xbox 360                       ",
"293 | Dota 2                                              | MOBA                    | Valve                                                      | PC                                                ",
"294 | Grand Theft Auto V                                  | Action-adventure        | Rockstar Games                                             | PlayStation 3, Xbox 360                           ",
"295 | The Last of Us                                      | Action-adventure        | Sony Computer Entertainment                                | PlayStation 3                                     ",
"296 | Papers, Please                                      | Puzzle                  | 3909 LLC                                                   | PC, Macintosh                                     ",
"297 | Destiny                                             | First-person shooter    | Bungie                                                     | PlayStation 3, PlayStation 4, Xbox 360, Xbox One  ",
"298 | Shovel Knight                                       | Platform                | Yacht Club Games                                           | Nintendo 3DS, PC, Wii U                           ",
"299 | Bloodborne                                          | Action role-playing     | Sony Computer Entertainment                                | PlayStation 4                                     ",
"300 | Rocket League                                       | Sports                  | Psyonix                                                    | PC, PlayStation 4                                 ",
"301 | Undertale                                           | Role-playing            | Toby Fox                                                   | PC, Macintosh                                     ",
"302 | The Witcher 3: Wild Hunt                            | Action role-playing     | CD Projekt                                                 | PC, PlayStation 4, Xbox One                       ",
"303 | Inside                                              | Platform                | Playdead                                                   | Xbox One                                          ",
"304 | Overwatch                                           | First-person shooter    | Blizzard Entertainment                                     | PC, PlayStation 4, Xbox One                       ",
"305 | Stardew Valley                                      | Simulation              | ConcernedApe                                               | PC                                                ",
"306 | Uncharted 4: A Thief's End                          | Action-adventure        | Sony Computer Entertainment                                | PlayStation 4                                     ",
"307 | The Legend of Zelda: Breath of the Wild             | Action-adventure        | Nintendo                                                   | Nintendo Switch, Wii U                            ",
"308 | Super Mario Odyssey                                 | Platform                | Nintendo                                                   | Nintendo Switch                                   ",
"309 | God of War                                          | Action-adventure        | Sony Interactive Entertainment                             | PlayStation 4                                     ",
"310 | Red Dead Redemption 2                               | Action-adventure        | Rockstar Games                                             | PlayStation 4, Xbox One                           ",
    
]

f = open("games.html", "w")
f.write('<h1>Giochi</h1>')
f.write('<ul>')
for gioco in giochi:
    info = gioco.split("|")

    id, nome, genere, publisher , piattaforma = info

    f.write(f"<li>{nome}</li>")
    
f.write('</ul>')

f.close()

print("siamo liberi")